# Generated by Django 3.2 on 2021-06-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20210616_0231'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecv',
            name='link',
            field=models.CharField(db_index=True, default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecv',
            name='telefone',
            field=models.CharField(db_index=True, default=2, max_length=200),
            preserve_default=False,
        ),
    ]
